FROM node:18-alpine
LABEL org.opencontainers.image.source='https://github.com/shin6949/twitch-webhook-to-discord'

WORKDIR /app
COPY . .
RUN npm install
RUN export BUILD_STATUS="true" && \
        npm run build && \
        unset BUILD_STATUS && \
        rm .env

EXPOSE 3000

CMD ["npm", "start"]
