version: '3.1'
services:
  twitcheventsub:
    image: ghcr.io/shin6949/twitcheventsub:latest
    container_name: twitcheventsub
    ports:
      - "8080:8080"
    environment:
      - "DB_URL=jdbc:mariadb://{DB_URL}:{DB_PORT}/{DB_NAME}"
      - "DB_USER={DB_USER}"
      - "DB_PASSWORD={DB_PASSWORD}"
      - "TWITCH_CLIENT_ID={TWITCH_CLIENT_ID}"
      - "TWITCH_EVENT_SECRET={TWITCH_EVENT_SECRET}"
      - "WEBAPP_BASE_URL={BASE_URL}"
      - "TZ=Asia/Seoul"
      - "TWITCH_LOGO_URL="
      - "YOUTUBE_API_KEY="
      - "YOUTUBE_LOGO_URL="
    restart: always