message:
  basenames: string/string

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    # DB Config
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    # hikari
    hikari:
      connection-timeout: 9000
      idle-timeout: 20000
      max-lifetime: 30000

  devtools:
    livereload:
      enabled: false

  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

twitch:
  client-id: ${TWITCH_CLIENT_ID}
  client-secret: ${TWITCH_CLIENT_SECRET}
  event-secret: ${TWITCH_EVENT_SECRET}
  event-renew: true
  api-endpoint: https://api.twitch.tv/helix
  token-endpoint: https://id.twitch.tv/oauth2

webapp:
  base-url: ${WEBAPP_BASE_URL}

logging:
  level:
    root: info
---
spring:
  profiles: dev
  datasource:
    # DB Config
    url: jdbc:h2:./test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  hibernate:
    ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: debug

twitch:
  api-endpoint: http://localhost:3000/mock
  token-endpoint: http://localhost:3000/auth