name: Make Docker Image

on:
  push:
    tags:
      - V*

jobs:
  make-jar:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/Ver.}" >> $GITHUB_ENV

      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: 'microsoft'

      - name: Cache Gradle packages
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Package With Gradle
        run: gradle build

      - name: Move app file
        run: mv ./build/libs/twitchwebhook*.jar ./twitchwebhook-${{ env.RELEASE_VERSION }}.jar

      - name: Upload jar file to Artifact
        uses: actions/upload-artifact@3.1.1
        with:
          name: twitchwebhook
          path: ./twitchwebhook-${{ env.RELEASE_VERSION }}.jar
          retention-days: 1

  qemu-build:
    needs: make-jar
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download app from Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: twitchwebhook

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/Ver.}" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Move jar file
        run: |
          mkdir build && mkdir build/libs
          mv ./twitchwebhook/twitchwebhook-${{ env.RELEASE_VERSION }}.jar ./build/libs/twitchwebhook-${{ env.RELEASE_VERSION }}.jar

      - name: Docker Build
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/twitcheventsub:latest --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/twitcheventsub:${{ env.RELEASE_VERSION }} --push .