name: Make Docker Image

on:
  push:
    tags:
      - V*

jobs:
  make-jar:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/Ver.}" >> $GITHUB_ENV

      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Load Maven Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make Package With Maven
        run: mvn package

      - name: Move app file
        run: mv ./target/twitchwebhook*.jar ./twitchwebhook-${{ env.RELEASE_VERSION }}.jar

      - name: Upload jar file to Artifact
        uses: actions/upload-artifact@master
        with:
          name: twitchwebhook
          path: ./twitchwebhook-${{ env.RELEASE_VERSION }}.jar
          retention-days: 1

  qemu-build:
    needs: make-jar
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download app from Artifact
        uses: actions/download-artifact@v1
        with:
          name: twitchwebhook

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/Ver.}" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Move jar file
        run: |
          mkdir target
          mv twitchwebhook ./target/twitchwebhook-${{ env.RELEASE_VERSION }}.jar

      - name: Docker Build
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/twitcheventsub:latest --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/twitcheventsub:${{ env.RELEASE_VERSION }} --push .